/* Code generated by Cyberia stat-contract. DO NOT EDIT. */
#ifndef CYBERIA_STAT_CONTRACT_H
#define CYBERIA_STAT_CONTRACT_H
#define CYBERIA_STAT_COUNT 6
static const char* const CYBERIA_STAT_NAMES[CYBERIA_STAT_COUNT] = {"effect", "resistance", "agility", "range", "intelligence", "utility"};
typedef struct {
    int effect;
    int resistance;
    int agility;
    int range;
    int intelligence;
    int utility;
} Stats;
static inline void cyberia_stats_values(const Stats* stats, int values[CYBERIA_STAT_COUNT]) {
    values[0] = stats->effect;
    values[1] = stats->resistance;
    values[2] = stats->agility;
    values[3] = stats->range;
    values[4] = stats->intelligence;
    values[5] = stats->utility;
}
static inline Stats cyberia_stats_from_values(const int values[CYBERIA_STAT_COUNT]) {
    return (Stats){values[0], values[1], values[2], values[3], values[4], values[5]};
}
static const char* const CYBERIA_STAT_ICONS[CYBERIA_STAT_COUNT] = {"stat-effect", "stat-resistance", "stat-agility", "stat-range", "stat-intelligence", "stat-utility"};
static const char* const CYBERIA_STAT_LABELS[CYBERIA_STAT_COUNT] = {"Effect", "Resistance", "Agility", "Range", "Intelligence", "Utility"};
#endif
