#include "object_layers_management.c"

#include <assert.h>
#include <stdio.h>
#include <string.h>

/* The WebSocket metadata message carries one immutable definition per item label. The
 * fixture is generated by the engine from the same definition the Go server is tested
 * against, so the three runtimes name one identity. */

/* The identity the engine computes for the contract definition. */
#define CONTRACT_CID "bafkreihbdxmw6pzohkabf3pxtvqytnmkfi6h6f3ovmihp7vb6g7im3fule"
#define CONTRACT_RENDER_CID "bafkreidksiktki2pjijlf63djoorcifkov56idvalevbj4clakjz7mvl3q"
#define CONTRACT_METADATA_CID "bafkreigcohqyadv5kpqjoph2m4s53wfmu5pvuaufgwilobl7n4hxgha6hm"

void fetch_data_release(void* data) { (void)data; }
void fetch_request_start_at(const char* id, const char* url, FetchCompletedCb callback, FetchPriority priority) {
    (void)id; (void)url; (void)callback; (void)priority;
}
Texture2D fetch_texture(const char* url, int pixel_scale, FetchPriority priority, bool visible) {
    (void)url; (void)pixel_scale; (void)priority; (void)visible;
    return (Texture2D){0};
}
void fetch_visible(const char* url) { (void)url; }

static char* read_file(const char* path) {
    FILE* file = fopen(path, "rb");
    assert(file);
    fseek(file, 0, SEEK_END);
    long size = ftell(file);
    fseek(file, 0, SEEK_SET);
    char* text = malloc((size_t)size + 1);
    assert(text);
    assert(fread(text, 1, (size_t)size, file) == (size_t)size);
    text[size] = '\0';
    fclose(file);
    return text;
}

int main(void) {
    create_object_layers_manager();

    char* text = read_file("tests/testdata/ws_object_layer_metadata.json");
    cJSON* root = cJSON_Parse(text);
    assert(root);
    cJSON* entry = NULL;
    cJSON_ArrayForEach(entry, root) { populate_object_layer_from_json(entry->string, entry); }

    const ObjectLayer* sword = lookup_cached_layer("sword");
    assert(sword);
    assert(strcmp(sword->cid, CONTRACT_CID) == 0);
    assert(strcmp(sword->data.item.id, "sword") == 0);
    assert(strcmp(sword->data.item.type, "weapon") == 0);
    assert(sword->data.stats.effect == -100);
    assert(sword->data.stats.resistance == 100);
    assert(sword->data.ledger.standard == LEDGER_UNREGISTERED);
    assert(strcmp(sword->data.render.cid, CONTRACT_RENDER_CID) == 0);
    assert(strcmp(sword->data.render.metadata_cid, CONTRACT_METADATA_CID) == 0);

    /* A registered definition carries its ItemLedger binding; the content is unchanged. */
    const char* registered =
        "{\"cid\":\"" CONTRACT_CID "\",\"data\":{\"stats\":{},"
        "\"item\":{\"id\":\"sword\",\"type\":\"weapon\"},\"ledger\":{\"standard\":\"ERC1155\","
        "\"chainId\":777771,\"contractAddress\":\"0xabc\",\"tokenId\":\"42\"},\"render\":{}}}";
    cJSON* bound = cJSON_Parse(registered);
    assert(bound);
    populate_object_layer_from_json("sword-registered", bound);
    const ObjectLayer* token = lookup_cached_layer("sword-registered");
    assert(token);
    assert(strcmp(token->cid, sword->cid) == 0);
    assert(token->data.ledger.standard == LEDGER_ERC1155);
    assert(token->data.ledger.chain_id == 777771);
    assert(strcmp(token->data.ledger.contract_address, "0xabc") == 0);
    assert(strcmp(token->data.ledger.token_id, "42") == 0);

    /* The render metadata is in cells whatever the pixel density of the primary render. */
    char metadata[] =
        "{\"data\":{\"metadata\":{\"itemKey\":\"sword\",\"atlasWidth\":4,\"atlasHeight\":2,"
        "\"cellPixelDim\":2,\"frame_duration\":120,\"frames\":{"
        "\"down_idle\":[{\"x\":2,\"y\":0,\"width\":2,\"height\":2,\"frameIndex\":0}],"
        "\"up_idle\":[],\"right_idle\":[],\"left_idle\":[],\"up_right_idle\":[],\"down_right_idle\":[],"
        "\"up_left_idle\":[],\"down_left_idle\":[],\"default_idle\":[],\"up_walking\":[],"
        "\"down_walking\":[],\"right_walking\":[],\"left_walking\":[],\"up_right_walking\":[],"
        "\"down_right_walking\":[],\"up_left_walking\":[],\"down_left_walking\":[],\"none_idle\":[]}}}}";
    on_atlas_meta_fetched(&(FetchResponse){.success = true, .data = metadata, .size = strlen(metadata)});
    const AtlasSpriteSheetData* atlas = hash_table_get(&g_olm_singleton->atlases, "sword");
    assert(atlas);
    assert(atlas->atlas_width == 4 && atlas->atlas_height == 2 && atlas->cell_pixel_dim == 2);
    assert(atlas->frame_duration == 120 && atlas->down_idle.count == 1);
    assert(atlas->down_idle.frames[0].x == 2 && atlas->down_idle.frames[0].width == 2);

    cJSON_Delete(bound);
    cJSON_Delete(root);
    free(text);
    destroy_object_layers_manager();
    puts("object_layer_metadata_test OK");
    return 0;
}
